# Generated by Django 5.0.6 on 2024-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Historical', 'Historical'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Personal Development', 'Personal Development'), ('Cookbooks', 'Cookbooks'), ('Romance', 'Romance'), ('Story', 'Story'), ('Biography', 'Biography')], max_length=50),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('borrowed_books', models.ManyToManyField(blank=True, related_name='borrowers', to='pages.book')),
            ],
        ),
    ]
