# Generated by Django 3.2.12 on 2024-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='User',
            name='email',
            field=models.EmailField(max_length=254, unique=True, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='password',
            field=models.CharField(max_length=128, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='is_admin',
            field=models.BooleanField(max_length=10, null=False),  
        ),
    ]
