# Generated by Django 3.2.12 on 2024-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20240515_0733'),
    ]

    operations = [
      migrations.AddField(
            model_name='User',
            name='email',
            field=models.EmailField(max_length=254, unique=True, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='password',
            field=models.CharField(max_length=128, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='is_admin',
            field=models.BooleanField(max_length=10, null=False),  
        ),
    ]
