# Generated by Django 5.0.6 on 2024-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_user_email_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
        model_name='User',
        name='email',
        field=models.EmailField(max_length=254, unique=True, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='password',
            field=models.CharField(max_length=128, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='is_admin',
            field=models.BooleanField(max_length=10, null=False),  
        ),
        migrations.AddField(
            model_name='User',
            name='fullname',
            field=models.CharField(max_length=255, null=False),  
        ),
    ]
